# See the writing guide of rbs: https://github.com/ruby/rbs#guides
module STAC
  def self.from_file: (String path) -> (Catalog | Collection | Item)
  %a{rbs:test:skip} def self.from_url: (String url, ?http_client: _HTTPClient) -> (Catalog | Collection | Item)
end
