# See the writing guide of rbs: https://github.com/ruby/rbs#guides
module STAC
  attr_accessor self.default_http_client: _HTTPClient

  def self.from_file: (String path) -> (Catalog | Collection | Item)
  def self.from_url: (String url, ?http_client: _HTTPClient) -> (Catalog | Collection | Item)

  interface _HTTPClient
    def get: (URI::Generic | String url) -> Hash[String, untyped]
  end
end
