module STAC
  class Asset
    include CommonMetadata

    def self.from_hash: (Hash[String, untyped] hash) -> Asset

    attr_accessor href: String
    attr_accessor title: String?
    attr_accessor description: String?
    attr_accessor type: String?
    attr_accessor roles: Array[String]?
    attr_accessor extra: Hash[String, untyped]

    def initialize: (
      href: String, ?title: String?, ?description: String?, ?type: String?, ?roles: Array[String]?, **untyped
    ) -> void

    def to_h: -> Hash[String, untyped]
  end
end
