module STAC
  class Asset
    include HashLike
    include CommonMetadata

    def self.from_hash: (Hash[String, untyped] hash) -> Asset

    attr_accessor href: String
    attr_accessor title: String?
    attr_accessor description: String?
    attr_accessor type: String?
    attr_accessor roles: Array[String]?

    def initialize: (
      href: String, ?title: String?, ?description: String?, ?type: String?, ?roles: Array[String]?, **untyped
    ) -> void
  end
end
