module STAC
  class Catalog < STACObject
    def self.from_hash: (Hash[String, untyped] hash) -> Catalog

    attr_accessor id: String
    attr_accessor description: String
    attr_accessor title: String?
    
    def initialize: (
      id: String, description: String, links: Array[Hash[String, String]], ?title: String?, ?stac_extensions: Array[String], **untyped
    ) -> void

    def children: -> Enumerator::Lazy[Catalog | Collection, void]
    def collections: -> Enumerator::Lazy[Collection, void]
    def find_child: (String id, ?recursive: bool) -> (Catalog | Collection | nil)
    def items: -> Enumerator::Lazy[Item, void]
    def all_items: -> Enumerator::Lazy[Item, void]
    def find_item: (String id, ?recursive: bool) -> Item?
  end
end
