module STAC
  class DefaultHTTPClient
    attr_reader options: Hash[String, String]

    def initialize: (?Hash[String, String] options) -> void

    def get: (URI uri) -> String
  end

  interface _HTTPClient
    def get: (URI uri) -> String
  end
end
