module STAC
  class Error < StandardError
  end

  class TypeError < Error
  end

  class UnknownURISchemeError < Error
  end

  class HTTPError < Error
  end

  class ExtensionWithoutIdentifierError < Error
  end
end
