module STAC
  module Extension
    @identifier: String?
    @scope: Array[Class]?

    def identifier: -> String | (String) -> String
    def scope: -> Array[Class] | (*Class) -> Array[Class]
  end
end
