module STAC
  class FileWriter
    @hash_to_json: ^(Hash[String, untyped]) -> String

    def initialize: (?hash_to_json: ^(Hash[String, untyped]) -> String) -> void

    def write: (Hash[String, untyped], dest: String) -> void
  end

  interface _Writer
    def write: (Hash[String, untyped], dest: String) -> void
  end
end
