module STAC
  class Item < STACObject
    def self.from_hash: (Hash[String, untyped] hash) -> Item

    attr_accessor geometry: Hash[String, untyped]?
    attr_accessor properties: Hash[String, untyped]
    attr_accessor assets: Hash[String, Asset]
    attr_accessor bbox: Array[Numeric]?
    attr_accessor collection: String?

    def initialize: (
      id: String,
      geometry: Hash[String, untyped]?,
      properties: Hash[String, untyped],
      links: Array[Link],
      assets: Hash[String, Asset],
      ?bbox: Array[Numeric]?,
      ?collection: String?,
      ?stac_extensions: Array[String]?,
      **untyped
    ) -> void
  end
end
