module STAC
  class Item < STACObject
    def self.from_hash: (Hash[String, untyped] hash) -> Item

    attr_accessor geometry: Hash[String, untyped]?
    attr_accessor properties: Properties
    attr_accessor assets: Hash[String, Asset]
    attr_accessor bbox: Array[Numeric]?
    attr_accessor collection_id: String?

    def initialize: (
      id: String,
      geometry: Hash[String, untyped]?,
      properties: Properties,
      links: Array[Link],
      assets: Hash[String, Asset],
      ?bbox: Array[Numeric]?,
      ?collection: String | Collection | nil,
      ?stac_extensions: Array[String]?,
      **untyped
    ) -> void

    def datetime: -> Time?
    def collection: -> Collection?
    def collection=: (Collection collection) -> void
  end
end
