module STAC
  class Link
    include HashLike

    def self.from_hash: (Hash[String, untyped]) -> Link

    attr_accessor rel: String
    attr_accessor href: String
    attr_accessor type: String?
    attr_accessor title: String?
    attr_accessor owner: STACObject?
    attr_accessor http_client: _HTTPClient
    @target: STACObject?
    @resolver: ObjectResolver

    def initialize: (rel: String, href: String, ?type: String?, ?title: String?, **untyped) -> void

    def absolute_href: -> String?
    def target: (?http_client: _HTTPClient) -> STACObject?
  end
end
