module STAC
  class LinkHrefError < Error
    attr_reader link: Link

    def initialize: (?String? msg, link: Link) -> void
  end

  class Link
    include HashLike

    def self.from_hash: (Hash[String, untyped]) -> Link

    attr_accessor rel: String
    attr_writer href: String?
    attr_accessor type: String?
    attr_accessor title: String?
    attr_accessor owner: STACObject?
    attr_accessor http_client: _HTTPClient
    @target: STACObject?
    @resolver: ObjectResolver

    def initialize: (?STACObject? target, rel: String, href: String?, ?type: String?, ?title: String?, **untyped) -> void
    def resolved?: -> bool
    def href: -> String?
    def absolute_href: -> String?
    def relative_href: -> String?
    def target: (?http_client: _HTTPClient) -> STACObject?
    
    def href!: -> String
    def absolute_href!: -> String
    def relative_href!: -> String
  end
end
