module STAC
  class ObjectResolver
    attr_writer self.default_http_client: _HTTPClient

    def self.default_http_client: -> _HTTPClient

    attr_reader http_client: _HTTPClient

    def initialize: (?http_client: _HTTPClient) -> void

    def resolve: (String url) -> (Catalog | Collection)

    private

    def read: (String url) -> String
  end

  interface _HTTPClient
    def get: (URI uri) -> String
  end
end
