module STAC
  class ObjectResolver
    RESOLVABLES: Array[_STACObjectClass]

    attr_accessor self.resolvables: Array[_STACObjectClass]

    def self.default_http_client: -> _HTTPClient

    attr_reader http_client: _HTTPClient

    def initialize: (http_client: _HTTPClient) -> void

    def resolve: (String url) -> (Catalog | Collection | Item)

    private

    def read: (String url) -> Hash[String, untyped]
  end

  interface _STACObjectClass
    def type: -> String
    def from_hash: (Hash[String, untyped] hash) -> untyped
  end
end
