module STAC
  class Properties
    include HashLike
    include CommonMetadata

    def self.from_hash: (Hash[String, untyped] hash) -> Properties

    attr_accessor datetime: Time?

    def initialize: (datetime: Time?, **untyped) -> void
  end
end
