module STAC
  class STACObject
    attr_accessor self.type: String
    
    def self.from_hash: (Hash[String, untyped]) -> STACObject
    
    attr_accessor stac_extensions: Array[String]?
    attr_accessor extra: Hash[String, untyped]
    attr_accessor http_client: _HTTPClient
    attr_reader links: Array[Link]

    def initialize: (
      links: Array[Link], ?stac_extensions: Array[String]?, **untyped
    ) -> void

    def type: -> String
    def to_h: -> Hash[String, untyped]
    def to_json: -> String
    def add_link: (Link) -> Array[Link]
    def self_href: -> String?
    def self_href=: (String) -> void
    def find_link: (rel: String, ?type: String?) -> Link?

    private

    def remove_link: (rel: String) -> Array[Link]?
  end
end
