name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup spec/fixtures
        run: bundle exec rake fixture:setup

      - name: Run the default task
        run: bundle exec rake
        env:
          RBS_TEST_TARGET: STAC::*
          RBS_TEST_OPT: -r uri -I sig
          RBS_TEST_DOUBLE_SUITE: rspec
          RUBYOPT: -r bundler/setup -r rbs/test/setup
          RBS_TEST_LOGLEVEL: warn
